{% set name = "aiohttp-client-cache" %}
{% set version = "0.4.1" %}
{% set hash_val = "5fe10f1ddd29eea02031176b6b8a6f3b4742738ee52e1ffd061b5c7bd78dbfb9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - aiohttp[speedups] >=3.0
    - aiosqlite >=0.16
    - aioredis >=1.3
    - attrs >=21.2
    - itsdangerous >=1.1
    - python-forge >=18.6
    - url-normalize >=1.4

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - aiohttp_client_cache
    - aiohttp_client_cache.backends

about:
  home: https://github.com/JWCook/aiohttp-client-cache
  summary: Persistent cache for aiohttp requests
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/JWCook/aiohttp-client-cache
  doc_url: https://aiohttp-client-cache.readthedocs.io

extra:
  recipe-maintainers:
    - JWCook
